accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import login_view, home
from .views import admin_dashboard
from . import views


urlpatterns = [

    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('admin-panel/dashboard/', admin_dashboard, name='admin_dashboard'),

]

ehospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('admin-panel/', include('adminapp.urls')),
    path('patient/', include('patientapp.urls')),
    path('doctors/', include('doctorapp.urls')),
    path('facility/', include('facility.urls')),

]


if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patientapp/models.py
from django.db import models

from accounts.models import User



# models.py
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, null=True, blank=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)

    def __str__(self):
        return self.full_name or self.user.username



class Appointment(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Cancelled', 'Cancelled'),
        ('Completed', 'Completed'),
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey('doctorapp.Doctor', on_delete=models.CASCADE,null=True)
    department = models.ForeignKey('facility.Department', on_delete=models.CASCADE)
    location = models.ForeignKey('facility.Location', on_delete=models.CASCADE,null=True)  # NEW FIELD
    date = models.DateField()
    time = models.TimeField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True,null=True)


    def __str__(self):
        return f"{self.patient.full_name} - {self.doctor.user.username} on {self.date}"





class MedicalRecord(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey('doctorapp.Doctor', on_delete=models.SET_NULL,
        null=True,
        blank=True)
    diagnosis = models.TextField()
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, null=True, blank=True)  # NEW
    prescription = models.TextField()
    allergies = models.TextField(blank=True, null=True)
    treatment_history = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Billing(models.Model):
    STATUS_CHOICES = [
        ('Unpaid', 'Unpaid'),
        ('Paid', 'Paid'),
    ]

    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
    appointment = models.ForeignKey('Appointment', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)   # consultation, lab test, surgery etc
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Unpaid')
    stripe_payment_intent_id = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.patient.full_name} - {self.amount} - {self.status}"


class Payment(models.Model):
    billing = models.ForeignKey(Billing, on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=10, choices=[('Pending','Pending'), ('Paid','Paid')])

    def __str__(self):
        return f"{self.billing} - {self.status}"



class HealthResource(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    link = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

templates/doctor/add_medical_record.html
{% extends "doctor/base.html" %}
{% block header %}Add Medical Record{% endblock %}

{% block content %}
<h6>Patient: {{ appointment.patient }}</h6>
<p>Appointment: {{ appointment.appointment_date }} {{ appointment.appointment_time }}</p>

<form method="post">
    {% csrf_token %}

    <label>Diagnosis</label>
    <textarea name="diagnosis" class="form-control" required></textarea>

    <label class="mt-2">Prescription</label>
    <textarea name="prescription" class="form-control" required></textarea>

    <label class="mt-2">Allergies</label>
    <textarea name="allergies" class="form-control"></textarea>

    <label class="mt-2">Treatment History</label>
    <textarea name="treatment_history" class="form-control"></textarea>

    <button class="btn btn-success mt-3">Save Medical Record</button>
</form>
{% endblock %}

templates/doctor/appointment_details.html
{% extends "doctor/base.html" %}
{% block title %}Appointment Detail{% endblock %}
{% load static %}
{% block header %}Appointment Detail{% endblock %}

{% block content %}

<!-- Font Awesome -->
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

<div class="container mt-4">

  <div class="row g-4">

    <!-- Patient Information -->
    <div class="col-md-5">
      <div class="card shadow-sm border-0">
        <div class="card-header text-white" style="background :#2f4050;">
          <i class="fa-solid fa-user"></i> Patient Information
        </div>
        <div class="card-body">
          <p><strong>Name:</strong> {{ appointment.patient }}</p>
          <p><strong>Age:</strong> {{ appointment.patient.age }}</p>
          <p><strong>Gender:</strong> {{ appointment.patient.gender }}</p>
          <p><strong>Phone:</strong> {{ appointment.patient.phone }}</p>
        </div>
      </div>
    </div>

    <!-- Appointment Information -->
    <div class="col-md-7">
      <div class="card shadow-sm border-0">
        <div class="card-header text-white" style="background :#2f4050;">
          <i class="fa-solid fa-calendar-check"></i> Appointment Details
        </div>

        <div class="card-body">
          <form method="post">
            {% csrf_token %}

            <div class="row mb-3">
              <div class="col-md-6">
                <label class="form-label">Date</label>
                <input type="date"
                       name="date"
                       class="form-control"
                       value="{{ appointment.date }}">
              </div>

              <div class="col-md-6">
                <label class="form-label">Time</label>
                <input type="time"
                       name="time"
                       class="form-control"
                       value="{{ appointment.time }}">
              </div>
            </div>

            <div class="mb-3">
              <label class="form-label">Status</label>
              <select name="status" class="form-select">
                {% for key, value in appointment.STATUS_CHOICES %}
                  <option value="{{ key }}"
                    {% if appointment.status == key %}selected{% endif %}>
                    {{ value }}
                  </option>
                {% endfor %}
              </select>
            </div>

            <!-- Buttons -->
            <div class="d-flex flex-wrap gap-2 mt-4">
              <button type="submit" class="btn btn-success">
                <i class="fa-solid fa-floppy-disk"></i> Update
              </button>

              <a href="{% url 'doctor_appointments' %}"
                 class="btn btn-secondary">
                <i class="fa-solid fa-arrow-left"></i> Back
              </a>

              <a href="{% url 'add_medical_record_from_appointment' appointment.id %}"
                 class="btn btn-primary ms-auto">
                <i class="fa-solid fa-notes-medical"></i> Add Medical Record
              </a>
            </div>

          </form>
        </div>
      </div>
    </div>

  </div>
</div>

{% endblock %}

templates/doctor/appointments.html
{% extends "doctor/base.html" %}
{% block title %}Appointments{% endblock %}
{% load static %}
{% block header %}My Appointments{% endblock %}

{% block content %}
<h3 class="mb-4"><strong>Appointments</strong></h3>
<div class="row mb-4">
<table class="comparison-table">
    <thead class="table-dark" >
        <tr>
            <th><i>Patient</i></th>
            <th><i>Date</i></th>
            <th><i>Time</i></th>
            <th><i>Created At</i></th>
            <th><i>Status</i></th>
            <th><i>Action</i></th>
        </tr>
    </thead>
    <tbody>
        {% for appt in appointments %}
        <tr>
            <td>{{ appt.patient }}</td>
            <td>{{ appt.date }}</td>
            <td>{{ appt.time }}</td>
            <td>{{ appt.created_at }}</td>
            <td>
                <span class="badge bg-info">{{ appt.status }}</span>
            </td>
            <td>
                <a href="{% url 'doctor_appointment_detail' appt.id %}"
                   class="btn btn-sm " style="background :#2f4050; color:white;">
                    View
                </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5" class="text-center">No appointments found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

templates/doctor/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>{% block title %}Doctor Dashboard{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
    <link rel="stylesheet" href="{% static 'css/doctor.css' %}">

    <style>
.profile-icon {
  width: 50px;               /* size of the circle */
  height: 50px;
  border-radius: 50%;        /* makes it circular */
  background-color: #007bff; /* blue background */
  color: white;              /* icon color */
  display: flex;
  align-items: center;
  justify-content: center;   /* center the icon */
  font-size: 24px;
}
</style>
</head>
<body>

 <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark p-4 fixed-top" style="background:#2f4050;">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarMenu">
            </div>
        </div>
    </nav>


<div class="container-fluid">
    <div class="row">

        <!-- Sidebar -->
        <nav class="col-md-2 sidebar">
             <ul>
                    <li>hello</li>
                </ul>
            <div class="profile-icon">

                <i class="fa-solid fa-user"></i>

            </div>
            <h6>Dr. {{ request.user.username }}</h6>

            <ul class="nav flex-column">
                <li class="nav-item"><a href="{% url 'doctor_dashboard' %}"><i class="fa fa-home"></i> Dashboard</a></li>
                <li class="nav-item"><a href="{% url 'doctor_appointments' %}"><i class="fa fa-calendar"></i> Appointments</a></li>
                <li class="nav-item"><a href="{% url 'doctor_patients' %}"><i class="fa fa-user"></i> Patients</a></li>
                <li class="nav-item"><a href="{% url 'doctor_medical_records' %}"><i class="fa fa-file-medical"></i> Medical Records</a></li>
                <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit" >
        <i class="fa-solid fa-right-from-bracket"></i> Logout
    </button>
</form>
            </ul>
        </nav>

        <!-- Main -->
        <main class="col-md-10 content">
            <br><br>
            {% block content %}{% endblock %}
        </main>

    </div>

</div>



</body>
</html>

templates/doctor/dashboard.html
{% extends "doctor/base.html" %}

{% block title %}Doctor Dashboard{% endblock %}
{% load static %}
{% block content %}

<h4 class="mb-4">Dashboard</h4>

<!-- Stats Cards -->
<div class="row mb-4">
    <div class="col-md-3">
        <div class="card stat-card">
            <h6>Total Patients</h6>
            <h2>{{ total_patients }}</h2>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card stat-card">
            <h6>Departments</h6>
            <h2>{{ total_departments }}</h2>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card stat-card">
            <h6>Total Appointments</h6>
            <h2>{{ total_appointments }}</h2>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card stat-card pending">
            <h6>Pending Appointments</h6>
            <h2>{{ pending_appointments }}</h2>
        </div>
    </div>
</div>



<!-- Patient List -->


        <h3><strong>New Patient List</strong></h3>
<div class="table-wrapper">
    <table class="comparison-table">
        <thead>
            <tr>
                <th>#</th>
                <th><i>Patient Name</i></th>
            <th><i>Date</i></th>
            <th><i>Time</i></th>
            <th><i>Status</i></th>
            </tr>
        </thead>
        <tbody>

        {% for appt in new_appointments %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ appt.patient }}</td>
            <td>{{ appt.date }}</td>
            <td>{{ appt.time }}</td>
            <td>
                <span class="badge bg-warning">
                    {{ appt.status }}
                </span>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No new appointments</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/doctor/medical_records.html
{% extends "doctor/base.html" %}
{% block title %}Medical Records{% endblock %}
{% block header %}My Medical Records{% endblock %}

{% block content %}

<h3 class="mb-4"><strong>Appointments</strong></h3>
<table class="comparison-table">
    <thead>
        <tr>
            <th><i>Patient</i></th>
            <th><i>Diagnosis</i></th>
            <th><i>Prescription</i></th>
            <th><i>Date</i></th>
        </tr>
    </thead>
    <tbody>
        {% for record in records %}
        <tr>
            <td>{{ record.patient }}</td>
            <td>{{ record.diagnosis|truncatechars:40 }}</td>
            <td>{{ record.prescription|truncatechars:40 }}</td>
            <td>{{ record.created_at|date:"d M Y" }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4" class="text-center">No medical records found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/doctor/patient_detail.html
{% extends "doctor/base.html" %}
{% block title %}Patient Detail{% endblock %}
{% load static %}
{% block header %}Patient: {{ patient.user.first_name }} {{ patient.user.last_name }}{% endblock %}

{% block content %}
<h4 class="mb-4"><strong>Patient Details</strong></h4>
<div class="card shadow-sm border-0">
<div class="card-header text-white" style="background :#2f4050;">
          <i class="fa-solid fa-user"></i> Basic Info
</div>
<div class="card-body">
<ul>
    <p><strong>Age:</strong> {{ patient.full_name }}</p>
    <p><strong>Age:</strong> {{ patient.age }}</p>
    <p><strong>Gender:</strong> {{ patient.gender }}</p>
    <p><strong>Phone:</strong> {{ patient.phone }}</p>
    <p><strong>Address:</strong> {{ patient.address }}</p>
</ul>
</div>
</div>
<h3 class="mb-4"><strong>Medical Records</strong></h3>
<table class="comparison-table">
    <thead>
        <tr>
            <th><i>Date</i></th>
            <th><i>Doctor</i></th>
            <th><i>Diagnosis</i></th>
            <th><i>Prescription</i></th>
        </tr>
    </thead>
    <tbody>
        {% for record in patient.medicalrecord_set.all %}
        <tr>
            <td>{{ record.created_at|date:"d M Y" }}</td>
            <td>{{ record.doctor }}</td>
            <td>{{ record.diagnosis }}</td>
            <td>{{ record.prescription }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No medical history</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/doctor/patient_list.html
{% extends "doctor/base.html" %}
{% block title %}Patients{% endblock %}
{% load static %}
{% block header %}My Patients{% endblock %}

{% block content %}
<h3 class="mb-4"><strong>Appointments</strong></h3>


<table class="comparison-table">
    <thead >
        <tr>
            <th><i>Patient Name</i></th>
            <th><i>Age</i></th>
            <th><i>Gender</i></th>
            <th><i>Actions</i></th>
        </tr>
    </thead>
    <tbody>
        {% for patient in patients %}
        <tr>
            <td>{{ patient.full_name }} </td>
            <td>{{ patient.age }}</td>
            <td>{{ patient.gender }}</td>
            <td>
                <a href="{% url 'doctor_patient_detail' patient.id %}" class="btn btn-sm " style="background :#2f4050; color:white;">View</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No patients assigned.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/doctor/prescriptions.html
{% extends "doctor/base.html" %}
{% block title %}Prescriptions{% endblock %}
{% block header %}My Prescriptions{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Patient</th>
            <th>Medication</th>
            <th>Dosage</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        {% for prescription in prescriptions %}
        <tr>
            <td>{{ prescription.patient.full_name }} </td>
            <td>{{ prescription.medication }}</td>
            <td>{{ prescription.dosage }}</td>
            <td>{{ prescription.date }}</td>
        </tr>
        {% empty %}
        <tr><td colspan="4">No prescriptions found.</td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}